config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    set_article
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    set_article
  end

  def update
    set_article
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    set_article
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edita un articulo</h1>
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<div class="container">
<% @articles.each do |article| %>
  <div class="article">
    <h2><%= link_to article.title, article_path(article.id) %></h2>
    <p> <%= article.content[0,200] %>
  </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>Crear un nuevo articulo</h1>
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<div class="container">
  <h1><%= @article.title %>
    <small>
    <%= link_to :edit_article do %>
      <i class='fa fa-pencil'></i>
    <% end %>
    <%= link_to article_path(@article.id), method: :delete, data: { confirm: "Estás seguro?" }  do %>
      <i class="fa fa-trash-o"></i>
    <% end %>
    </small>
  </h1>

  <div>
    <p><%= @article.content %></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <div class="logo">
    <%= link_to "Wikinimous", articles_path %>
    </div>
    <div class="new-article">
    <%= link_to "New Article", new_article_path %>
    </div>
    </nav>
    <%= yield %>
  </body>
</html>